# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkDB.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CheckDB(object):
    def setupUi(self, CheckDB):
        CheckDB.setObjectName("CheckDB")
        CheckDB.resize(564, 403)
        self.tableGroups = QtWidgets.QTableWidget(CheckDB)
        self.tableGroups.setGeometry(QtCore.QRect(10, 20, 539, 311))
        self.tableGroups.setColumnCount(3)
        self.tableGroups.setObjectName("tableGroups")
        self.tableGroups.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableGroups.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableGroups.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableGroups.setHorizontalHeaderItem(2, item)
        self.tableGroups.horizontalHeader().setDefaultSectionSize(179)
        self.pushButtonGroups = QtWidgets.QPushButton(CheckDB)
        self.pushButtonGroups.setGeometry(QtCore.QRect(30, 340, 121, 41))
        self.pushButtonGroups.setObjectName("pushButtonGroups")
        self.pushButtonVisitors = QtWidgets.QPushButton(CheckDB)
        self.pushButtonVisitors.setGeometry(QtCore.QRect(160, 340, 121, 41))
        self.pushButtonVisitors.setObjectName("pushButtonVisitors")
        self.pushButtonLessons = QtWidgets.QPushButton(CheckDB)
        self.pushButtonLessons.setGeometry(QtCore.QRect(290, 340, 121, 41))
        self.pushButtonLessons.setObjectName("pushButtonLessons")
        self.pushButtonBack = QtWidgets.QPushButton(CheckDB)
        self.pushButtonBack.setGeometry(QtCore.QRect(420, 340, 121, 41))
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.tableVisitors = QtWidgets.QTableWidget(CheckDB)
        self.tableVisitors.setGeometry(QtCore.QRect(10, 20, 542, 311))
        self.tableVisitors.setColumnCount(5)
        self.tableVisitors.setObjectName("tableVisitors")
        self.tableVisitors.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableVisitors.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVisitors.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVisitors.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVisitors.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVisitors.setHorizontalHeaderItem(4, item)
        self.tableVisitors.horizontalHeader().setDefaultSectionSize(108)
        self.tableVisitors.verticalHeader().setVisible(False)
        self.tableLessons = QtWidgets.QTableWidget(CheckDB)
        self.tableLessons.setGeometry(QtCore.QRect(10, 20, 542, 311))
        self.tableLessons.setColumnCount(4)
        self.tableLessons.setObjectName("tableLessons")
        self.tableLessons.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableLessons.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLessons.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLessons.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLessons.setHorizontalHeaderItem(3, item)
        self.tableLessons.horizontalHeader().setDefaultSectionSize(135)

        self.retranslateUi(CheckDB)
        QtCore.QMetaObject.connectSlotsByName(CheckDB)

    def retranslateUi(self, CheckDB):
        _translate = QtCore.QCoreApplication.translate
        CheckDB.setWindowTitle(_translate("CheckDB", "База данных"))
        item = self.tableGroups.horizontalHeaderItem(0)
        item.setText(_translate("CheckDB", "Название группы"))
        item = self.tableGroups.horizontalHeaderItem(1)
        item.setText(_translate("CheckDB", "Количество посетителей"))
        item = self.tableGroups.horizontalHeaderItem(2)
        item.setText(_translate("CheckDB", "ID Посетителей"))
        self.pushButtonGroups.setText(_translate("CheckDB", "Группы"))
        self.pushButtonVisitors.setText(_translate("CheckDB", "Посетители"))
        self.pushButtonLessons.setText(_translate("CheckDB", "Занятия"))
        self.pushButtonBack.setText(_translate("CheckDB", "Назад"))
        item = self.tableVisitors.horizontalHeaderItem(0)
        item.setText(_translate("CheckDB", "Идентификатор"))
        item = self.tableVisitors.horizontalHeaderItem(1)
        item.setText(_translate("CheckDB", "ФИО"))
        item = self.tableVisitors.horizontalHeaderItem(2)
        item.setText(_translate("CheckDB", "Осталось"))
        item = self.tableVisitors.horizontalHeaderItem(3)
        item.setText(_translate("CheckDB", "Посещено"))
        item = self.tableVisitors.horizontalHeaderItem(4)
        item.setText(_translate("CheckDB", "Группа"))
        item = self.tableLessons.horizontalHeaderItem(0)
        item.setText(_translate("CheckDB", "Дата"))
        item = self.tableLessons.horizontalHeaderItem(1)
        item.setText(_translate("CheckDB", "Группа"))
        item = self.tableLessons.horizontalHeaderItem(2)
        item.setText(_translate("CheckDB", "Кол-во посетителей"))
        item = self.tableLessons.horizontalHeaderItem(3)
        item.setText(_translate("CheckDB", "ID посетителей"))

