# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laba2.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(549, 398)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonTraining = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonTraining.setGeometry(QtCore.QRect(30, 280, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTraining.setFont(font)
        self.pushButtonTraining.setObjectName("pushButtonTraining")
        self.checkBoxRCause = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxRCause.setGeometry(QtCore.QRect(380, 90, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxRCause.setFont(font)
        self.checkBoxRCause.setChecked(False)
        self.checkBoxRCause.setObjectName("checkBoxRCause")
        self.pushButtonAbsent = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAbsent.setGeometry(QtCore.QRect(360, 40, 131, 41))
        self.pushButtonAbsent.setObjectName("pushButtonAbsent")
        self.pushButtonSubscribtion = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSubscribtion.setGeometry(QtCore.QRect(360, 170, 131, 41))
        self.pushButtonSubscribtion.setObjectName("pushButtonSubscribtion")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 90, 331, 181))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.comboBoxGroups = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxGroups.setGeometry(QtCore.QRect(10, 20, 331, 24))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.comboBoxGroups.setFont(font)
        self.comboBoxGroups.setEditable(False)
        self.comboBoxGroups.setCurrentText("")
        self.comboBoxGroups.setObjectName("comboBoxGroups")
        self.comboBoxVisitors = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxVisitors.setGeometry(QtCore.QRect(10, 50, 331, 22))
        self.comboBoxVisitors.setObjectName("comboBoxVisitors")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(380, 220, 31, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(430, 220, 31, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEditUser = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditUser.setGeometry(QtCore.QRect(420, 330, 121, 20))
        self.lineEditUser.setReadOnly(True)
        self.lineEditUser.setObjectName("lineEditUser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 310, 81, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 21))
        self.menubar.setObjectName("menubar")
        self.menuFitnessCenter = QtWidgets.QMenu(self.menubar)
        self.menuFitnessCenter.setObjectName("menuFitnessCenter")
        self.menuReference = QtWidgets.QMenu(self.menubar)
        self.menuReference.setObjectName("menuReference")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCheckDB = QtWidgets.QAction(MainWindow)
        self.actionCheckDB.setObjectName("actionCheckDB")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveLog = QtWidgets.QAction(MainWindow)
        self.actionSaveLog.setObjectName("actionSaveLog")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAboutProgramm = QtWidgets.QAction(MainWindow)
        self.actionAboutProgramm.setObjectName("actionAboutProgramm")
        self.actionAboutAuthor = QtWidgets.QAction(MainWindow)
        self.actionAboutAuthor.setObjectName("actionAboutAuthor")
        self.actionGroups = QtWidgets.QAction(MainWindow)
        self.actionGroups.setObjectName("actionGroups")
        self.actionVisitors = QtWidgets.QAction(MainWindow)
        self.actionVisitors.setObjectName("actionVisitors")
        self.actionStatusGr = QtWidgets.QAction(MainWindow)
        self.actionStatusGr.setObjectName("actionStatusGr")
        self.menuFitnessCenter.addAction(self.actionGroups)
        self.menuFitnessCenter.addAction(self.actionVisitors)
        self.menuFitnessCenter.addAction(self.actionStatusGr)
        self.menuFitnessCenter.addAction(self.actionSaveLog)
        self.menuFitnessCenter.addAction(self.actionCheckDB)
        self.menuReference.addAction(self.actionHelp)
        self.menuReference.addAction(self.actionAboutProgramm)
        self.menuReference.addAction(self.actionAboutAuthor)
        self.menubar.addAction(self.menuFitnessCenter.menuAction())
        self.menubar.addAction(self.menuReference.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Система отслеживания посещения занятий фитнесс-центра"))
        self.pushButtonTraining.setText(_translate("MainWindow", "Провести занятие"))
        self.checkBoxRCause.setText(_translate("MainWindow", "Ув. причина"))
        self.pushButtonAbsent.setText(_translate("MainWindow", "Отсутствует"))
        self.pushButtonSubscribtion.setText(_translate("MainWindow", "Пополнить абонемент"))
        self.radioButton.setText(_translate("MainWindow", "8"))
        self.radioButton_2.setText(_translate("MainWindow", "16"))
        self.label.setText(_translate("MainWindow", "Вы вошли как"))
        self.menuFitnessCenter.setTitle(_translate("MainWindow", "Фитнес-центр"))
        self.menuReference.setTitle(_translate("MainWindow", "Справка"))
        self.actionCheckDB.setText(_translate("MainWindow", "Просмотр БД"))
        self.actionSave.setText(_translate("MainWindow", "Сохранить"))
        self.actionSaveLog.setText(_translate("MainWindow", "Сохранить лог"))
        self.action_4.setText(_translate("MainWindow", "Закрыть"))
        self.actionHelp.setText(_translate("MainWindow", "Помощь"))
        self.actionAboutProgramm.setText(_translate("MainWindow", "О программе"))
        self.actionAboutAuthor.setText(_translate("MainWindow", "Об авторе"))
        self.actionGroups.setText(_translate("MainWindow", "Группы"))
        self.actionVisitors.setText(_translate("MainWindow", "Посетители"))
        self.actionStatusGr.setText(_translate("MainWindow", "Состояние группы"))

